name: Publish crates
on:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  publish:
      defaults:
         run:
            working-directory: wast
      name: Publish inf-wast
      runs-on: ubuntu-latest
      needs: build
      steps:
      - name: Cache Cargo registry
        uses: actions/cache@v4.2.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-
      - name: Install Dependencies
        run: cargo fetch
      - name: Build
        run: cargo build --release
      - name: Run Tests
        run: cargo test --release
      - name: Validate Package
        run: cargo package --allow-dirty
      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo publish --release
