name: Publish crates
on:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Publish inf-wast
      run: cargo publish -p inf-wast
    - name: Publish inf-wasmparser
      run: cargo publish -p inf-wasmparser
    - name: Publish wat-fmt
      run: cargo publish -p wat-fmt
